### ISSUE TITLE
Libre Office

### ISSUE THREAD

**Issue by Denorian24** [jakemanger/howtoconvert-support#16]
Hello,
When I tried to convert mp4 video to avi I got an error 

![Image](https://github.com/user-attachments/assets/19cea91e-6f7e-464f-bba9-74979be3bc98)

I  have Windows 10 64 bit

also after installing Libra Office my program does not see it

![Image](https://github.com/user-attachments/assets/c53658f4-f351-4bb3-8498-36e35f1338ca)
 
when I clicked on install ffmpeg it installed itself and the program saw it

and download Libra office redirected me to the official website from where I installed it manually.

By the way, where are the installed ffmpeg and pandoc stored?

**Comment by jakemanger** [comment]
Hi Denorian64,

I have just released v1.0.1 which can be downloaded at https://howtoconvert.co/dashboard

It fixes some conversion issues I found on windows and ads custom install location options for conversion tools:

![Image](https://github.com/user-attachments/assets/53e6dacd-0dcc-4cf1-afbf-b5698c9704de)

Could you give that a try and see if it resolves your issue?

**Comment by Denorian24** [comment]
Hello again!
I can't select a folder, instead it asks me to select a file

![Image](https://github.com/user-attachments/assets/f29a3cac-fb5a-4ed3-b0dd-5a75595fe68c)
and yes, it still doesn't work
but now I know where the application looks for Libra Office files)

**Comment by jakemanger** [comment]
Could you select the soffice.com file?

You shouldn't select a folder. A tooltip should appear explaining when you hover over the select location button

**Comment by Denorian24** [comment]
I selected the correct file and nothing seems to have changed. maybe I did something wrong

![Image](https://github.com/user-attachments/assets/5719cb26-806a-4cbd-9bd5-7759d91e6897)

**Comment by jakemanger** [comment]
Could you give converting something a try (ignoring the no libreoffice found message)

I am working on smoothing this process out now, so I'm sorry it's a bit of a pain. If that doesn't work for you, I should have a fix out today.

**Comment by jakemanger** [comment]
I have also just fixed a Windows path permissions issue that was occurring for some users. That will be available in v1.0.3 releasing today!
